### PR TITLE
Fix behaviour of CreateDataset in case of an timeout creating the image

### LINKED ISSUE #11: Error during CreateDataset should be cleaning up after an error happens
If a creation of a volume fails, it should make sure that it's removed from the Flocker API afterwards

Otherwise the volumes are created at a later point when the problems are resolved

### PR DESCRIPTION
**Pull request by simonswine**
- Old code did not return an error in the timeout case
- Delete dataset in case of a timeout
- Write test to ensure that timeouts are handled correctly
- fixes #11

### CODE REVIEW

File: client.go [hunk 1]
```diff
@@ -302,15 +302,25 @@ func (c *Client) CreateDataset(options *CreateDatasetOptions) (datasetState *Dat
...
 
 	for {
-		if s, err := c.GetDatasetState(p.DatasetID); err == nil {
+		var strErrDel string
+		s, err := c.GetDatasetState(p.DatasetID)
+		if err == nil {
 			return s, nil
 		} else if err != errStateNotFound {
-			return nil, err
+			errDel := c.DeleteDataset(p.DatasetID)
```
Comment (wallrj) [inline client.go:310]: :question: I'm not sure about this. Previously an error returned by `GetDatasetState` would be ignored and the function would continue to loop until the timeout....potentially recovering from a temporary error in the dataset state request. E.g. flocker-control is being restarted.

File: client.go [hunk 2]
```diff
@@ -302,15 +302,25 @@ func (c *Client) CreateDataset(options *CreateDatasetOptions) (datasetState *Dat
...
+			}
+			return nil, fmt.Errorf("Flocker API error during dataset creation: %s%s", err, strErrDel)
 		}
 
 		select {
 		case <-timeoutChan:
-			return nil, err
+			errDel := c.DeleteDataset(p.DatasetID)
+			if errDel != nil {
+				strErrDel = fmt.Sprintf(", deletion of dataset failed with %s", errDel)
```
Comment (wallrj) [inline client.go:321]: :question: Maybe include the `dataset_id` in this part of the error message.

File: client.go [hunk 3]
```diff
@@ -302,15 +302,25 @@ func (c *Client) CreateDataset(options *CreateDatasetOptions) (datasetState *Dat
...
+		s, err := c.GetDatasetState(p.DatasetID)
+		if err == nil {
 			return s, nil
 		} else if err != errStateNotFound {
-			return nil, err
+			errDel := c.DeleteDataset(p.DatasetID)
+			if errDel != nil {
+				strErrDel = fmt.Sprintf(", deletion of dataset failed with %s", errDel)
+			}
+			return nil, fmt.Errorf("Flocker API error during dataset creation: %s%s", err, strErrDel)
```
Comment (wallrj) [inline client.go]: :question: consider adding test coverage of this.

File: client.go [hunk 4]
```diff
@@ -302,15 +302,25 @@ func (c *Client) CreateDataset(options *CreateDatasetOptions) (datasetState *Dat
...
 		}
 
 		select {
 		case <-timeoutChan:
-			return nil, err
+			errDel := c.DeleteDataset(p.DatasetID)
+			if errDel != nil {
+				strErrDel = fmt.Sprintf(", deletion of dataset failed with %s", errDel)
+			}
+			return nil, fmt.Errorf("Flocker API timeout during dataset creation: %s%s", err, strErrDel)
```
Comment (wallrj) [inline client.go]: :question: And adding test coverage of this cleanup situation too.

File: client_test.go [hunk 5]
```diff
@@ -356,6 +356,70 @@ func TestCreateDatasetThatAlreadyExists(t *testing.T) {
...
+			assert.Equal("/v1/state/nodes", r.URL.Path)
+			w.Write([]byte(fmt.Sprintf(`[{"host": "127.0.0.1", "uuid": "%s"}]`, expectedPrimary)))
+		case 2:
+			assert.Equal("POST", r.Method)
+			assert.Equal("/v1/configuration/datasets", r.URL.Path)
+			w.Write([]byte(fmt.Sprintf(`{"dataset_id": "%s"}`, expectedDatasetID)))
+		default:
+			if r.Method == "GET" {
+				assert.Equal("/v1/state/datasets", r.URL.Path)
+				w.Write([]byte(`[]`))
```
Comment (wallrj) [inline client_test.go:388]: :question: Yeah, I don't think this is exercising the GetDatasetState error cleanup code...only the timeout situation. 
Another reason why I'd be inclined to only attempt the cleanup when dataset creation reaches a timeout.

File: client_test.go [hunk 6]
```diff
@@ -356,6 +356,70 @@ func TestCreateDatasetThatAlreadyExists(t *testing.T) {
...
+	c := newFlockerTestClient(host, port)
+
+	_, err = c.CreateDataset(&CreateDatasetOptions{
+		Metadata: map[string]string{
+			"name":    datasetName,
+			"primary": expectedPrimary,
+		},
+	})
+
+	assert.True(numCalls > 3, fmt.Sprintf("No enough retries getting dataset state: %d", numCalls))
```
Comment (wallrj) [inline client_test.go]: typo "No enough"

File: client_test.go [hunk 7]
```diff
@@ -356,6 +356,70 @@ func TestCreateDatasetThatAlreadyExists(t *testing.T) {
...
+	assert.True(deleted, "Failed dataset was not cleaned up afterwards")
+	assert.Equal("Flocker API timeout during dataset creation: State not found by Dataset ID", err.Error())
```
Comment (wallrj) [inline client_test.go]: Yeah, I'd say we should definitely include the dataset_id in this error....if possible.

**Comment by wallrj** [comment]
Thanks @simonswine 

I'd be interested to know whether Kubernetes dynamic volume provisioning fails unless we make this change.
In any case, please address or answer the comments above.

File: client_test.go (hunk 7 above)
Comment (simonswine) [reply client_test.go]: :+1:

File: client_test.go (hunk 6 above)
Comment (simonswine) [reply client_test.go]: :+1:

File: client_test.go (hunk 5 above)
Comment (simonswine) [reply client_test.go:388]: Ok added a failed cleanup test

File: client.go (hunk 4 above)
Comment (simonswine) [reply client.go]: :+1:

File: client.go (hunk 2 above)
Comment (simonswine) [reply client.go:321]: :+1:

File: client.go (hunk 1 above)
Comment (simonswine) [reply client.go:310]: I am not too sure how to handle this correctly. In terms of Kubernetes I am not really caring, as a failed provisioning will be retried endlessly..

**Comment by simonswine** [comment]
Thanks for reviewing @wallrj 

The biggest problem/bug right now for k8s dynamic provisioning is that if CreateDataset runs into a timeout, it will return `nil, nil` which crashes Kubernetes Controller Manager. This behaviour has to be fixed as soon as possible to move the dyn prov PR forward..

File: client.go [hunk 8]
```diff
@@ -302,15 +302,25 @@ func (c *Client) CreateDataset(options *CreateDatasetOptions) (datasetState *Dat
...
+			errDel := c.DeleteDataset(p.DatasetID)
+			if errDel != nil {
+				strErrDel = fmt.Sprintf(", deletion of dataset failed with %s", errDel)
+			}
+			return nil, fmt.Errorf("Flocker API error during dataset creation (datasetID %s): %s%s", p.DatasetID, err, strErrDel)
 		}
 
 		select {
 		case <-timeoutChan:
-			return nil, err
```
Comment (wallrj) [inline client.go:313]: In https://github.com/ClusterHQ/flocker-go/pull/12#issuecomment-247573709 @simonswine wrote:

> The biggest problem/bug right now for k8s dynamic provisioning is that if CreateDataset runs into a timeout, it will return nil, nil which crashes Kubernetes Controller Manager

Ah, so this is the important bit. It's returning `err` from the _successful_ API call above.

File: client.go (hunk 1 above)
Comment (wallrj) [reply client.go:310]: Ok. I'd be inclined to remove this since it seems unrelated to the Kubernetes crash bug, but if you think it's useful I'll go with it.

File: client_test.go (hunk 5 above)
Comment (wallrj) [reply client_test.go:388]: Thanks.

**Review by wallrj — APPROVED** [review]
Thanks @simonswine 

I think this looks ok and the new test adds more coverage.
I'll merge this so that we can get the dynamic provisioning merged into Kubernetes.
